# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pokitdok-ruby 0.9.2 ruby lib

Gem::Specification.new do |s|
  s.name = "pokitdok-ruby".freeze
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["PokitDok, Inc.".freeze]
  s.date = "2017-03-31"
  s.description = "Gem for easy access to the PokitDok Platform APIs.".freeze
  s.email = "platform@pokitdok.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/quick_start.rb",
    "lib/OAuthApplicationClient.rb",
    "lib/pokitdok.rb",
    "pokitdok-ruby.gemspec",
    "run_tests_in_docker.sh",
    "setup_and_test.sh",
    "spec/fixtures/acme_inc_supplemental_identifiers.834",
    "spec/fixtures/authorizations.json",
    "spec/fixtures/chiropractic_example.837",
    "spec/fixtures/claim.json",
    "spec/fixtures/claims_status.json",
    "spec/fixtures/enrollment.json",
    "spec/fixtures/identity_match.json",
    "spec/fixtures/referrals.json",
    "spec/fixtures/sample.270",
    "spec/fixtures/test_claim.837",
    "spec/pokitdok_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/pokitdok/pokitdok-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "Gem for easy access to the PokitDok Platform APIs".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth2>.freeze, ["~> 1.0"])
      s.add_runtime_dependency(%q<multipart-post>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<dotenv-rails>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<minitest>.freeze, ["~> 5.3"])
      s.add_development_dependency(%q<mocha>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.8"])
      s.add_development_dependency(%q<rubocop>.freeze, ["~> 0.20"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<ansi>.freeze, ["~> 1.4"])
      s.add_development_dependency(%q<minitest-reporters>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<guard>.freeze, ["~> 2.6"])
      s.add_development_dependency(%q<guard-minitest>.freeze, ["~> 2.2"])
      s.add_development_dependency(%q<terminal-notifier>.freeze, [">= 0"])
      s.add_development_dependency(%q<terminal-notifier-guard>.freeze, ["~> 1.5"])
      s.add_development_dependency(%q<guard-rubocop>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<coveralls>.freeze, [">= 0"])
      s.add_development_dependency(%q<rake>.freeze, ["< 11.0"])
    else
      s.add_dependency(%q<oauth2>.freeze, ["~> 1.0"])
      s.add_dependency(%q<multipart-post>.freeze, ["~> 2.0"])
      s.add_dependency(%q<dotenv-rails>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<minitest>.freeze, ["~> 5.3"])
      s.add_dependency(%q<mocha>.freeze, ["~> 1.0"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.8"])
      s.add_dependency(%q<rubocop>.freeze, ["~> 0.20"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<ansi>.freeze, ["~> 1.4"])
      s.add_dependency(%q<minitest-reporters>.freeze, ["~> 1.0"])
      s.add_dependency(%q<guard>.freeze, ["~> 2.6"])
      s.add_dependency(%q<guard-minitest>.freeze, ["~> 2.2"])
      s.add_dependency(%q<terminal-notifier>.freeze, [">= 0"])
      s.add_dependency(%q<terminal-notifier-guard>.freeze, ["~> 1.5"])
      s.add_dependency(%q<guard-rubocop>.freeze, ["~> 1.0"])
      s.add_dependency(%q<coveralls>.freeze, [">= 0"])
      s.add_dependency(%q<rake>.freeze, ["< 11.0"])
    end
  else
    s.add_dependency(%q<oauth2>.freeze, ["~> 1.0"])
    s.add_dependency(%q<multipart-post>.freeze, ["~> 2.0"])
    s.add_dependency(%q<dotenv-rails>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<minitest>.freeze, ["~> 5.3"])
    s.add_dependency(%q<mocha>.freeze, ["~> 1.0"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.8"])
    s.add_dependency(%q<rubocop>.freeze, ["~> 0.20"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<ansi>.freeze, ["~> 1.4"])
    s.add_dependency(%q<minitest-reporters>.freeze, ["~> 1.0"])
    s.add_dependency(%q<guard>.freeze, ["~> 2.6"])
    s.add_dependency(%q<guard-minitest>.freeze, ["~> 2.2"])
    s.add_dependency(%q<terminal-notifier>.freeze, [">= 0"])
    s.add_dependency(%q<terminal-notifier-guard>.freeze, ["~> 1.5"])
    s.add_dependency(%q<guard-rubocop>.freeze, ["~> 1.0"])
    s.add_dependency(%q<coveralls>.freeze, [">= 0"])
    s.add_dependency(%q<rake>.freeze, ["< 11.0"])
  end
end

